url:
  lc_employee_list_check: 
  lc_employee_list: 
credentials:
  primeuser: 
openair:
  company: 
  user: 
  password:
  proxy: 
  billable_report_id: 
  voluntary_report_id: 
labcase:
  user:
  password: 
  api_key: 
  project_name: 
  report_id:
mapping:
  - full_name1, acronym1
  - full_name2, acronym2