url:
  lc_employee_list_check: add_url
  lc_employee_list: add_url
credentials:
  primeuser: add_credentials
openair:
  company: add_name
  user: add_user
  password: add_password
  proxy: add_proxy_user
  billable_report_id: add_report_id
  voluntary_report_id: add_report_id
labcase:
  user: add_username
  password: add_password
  
  

