url:
  oa_prime_bookable: enter_url
  oa_prime_voluntary: enter_url
  lc_employee_list_check: entuer_url
  lc_employee_list: enter_url
  lc_task_list: enter_url
credentials:
  primeuser: enter_credentials

